apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.name }}
spec:
  ports:
  - name: {{ .Values.name }}
    port: {{ .Values.MONGO_VARS.DOT_port }}
    targetPort: {{ .Values.MONGO_VARS.DOT_port }}
  selector:
    role: {{ .Values.name }}
