apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  serviceName: {{ .Values.name }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      role: {{ .Values.name }}
  template:
    metadata:
      labels:
        role: {{ .Values.name }}
    spec:
      terminationGracePeriodSeconds: 300
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.Image.repository }}/{{ .Values.Image.name }}:{{ .Values.Image.tag }}
        imagePullPolicy: {{ .Values.Image.pullPolicy }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
        env:
        - name: DOT_port
          value: {{ .Values.MONGO_VARS.DOT_port | quote}}
        - name: MONGO_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name   
        - name: DOT_logappend
          value: {{ .Values.MONGO_VARS.DOT_logappend | quote }}
        - name: DOT_smallfiles
          value: {{ .Values.MONGO_VARS.DOT_smallfiles | quote }}
        - name: DOT_bind_ip
          value: {{ .Values.MONGO_VARS.DOT_bind_ip | quote}}
        ports:
        - name: {{ .Values.name }}
          containerPort: {{ .Values.MONGO_VARS.DOT_port }}
        livenessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: data
          mountPath: /mongo
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: {{ .Values.StorageClass | quote }}
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage:  {{ .Values.resources.requests.storage | quote }}
